@hostname = http://127.0.0.1
@port = 8888
@host = {{hostname}}:{{port}}
@baseUrl = {{host}}
@contentType = application/json


### Login to get the token
# @name authlogin
POST {{baseUrl}}/login
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="username"

user@gmail.coms
--boundary
Content-Disposition: form-data; name="password"

abababab
--boundary--
# Content-Disposition: form-data; name="image"; filename="1.png"
# Content-Type: image/png

# < ./1.png
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get token
@authToken = {{authlogin.response.body.access_token}}




### GET all ourse details 
GET {{baseUrl}}


### get the posts
GET {{baseUrl}}/post
Authorization: Bearer {{authToken}}


### get the posts
GET {{baseUrl}}/post/1
Authorization: Bearer {{authToken}}


### get the posts
GET {{baseUrl}}/post/latest


### Creaet the post
POST {{baseUrl}}/post
content-type: {{contentType}}

{
  "name": "Book",
  "content": "This is the blog detail",
  "price": 250
}


### Creaet the post
PUT {{baseUrl}}/post/13
content-type: {{contentType}}

{
  "name": "Note Book",
  "content": "This is the blog detail",
  "price": 200
}


### Delete the posts
DELETE {{baseUrl}}/post/12







### get the users
GET {{baseUrl}}/user


### get the specific users
GET {{baseUrl}}/user/1


### Creaet a new user
POST {{baseUrl}}/user
content-type: {{contentType}}

{
  "email": "user@gmail.comqs",
  "password": "abababab"
}


### Update the user
PUT {{baseUrl}}/user/1
content-type: {{contentType}}

{
  "email": "abhay4122@gmail.com",
  "password": "bbbbbbbb"
}


### Delete the user
DELETE {{baseUrl}}/user/11
